# Configuration Decap CMS
backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: 'Create {{collection}} "{{slug}}"'
    update: 'Update {{collection}} "{{slug}}"'
    delete: 'Delete {{collection}} "{{slug}}"'
    uploadMedia: 'Upload "{{path}}"'
    deleteMedia: 'Delete "{{path}}"'

media_folder: "public/images/uploads"
public_folder: "/images/uploads"
locale: 'fr'

collections:
  - name: "homepage"
    label: "Page d'Accueil"
    files:
      - file: "src/content/homepage/hero.md"
        label: "Hero Banner"
        name: "hero"
        fields:
          - {label: "Titre (H1)", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "text", hint: "Maximum 40 mots"}
          - {label: "Image de fond", name: "backgroundImage", widget: "image"}
          - {label: "Texte du bouton", name: "buttonText", widget: "string"}
          - {label: "URL du bouton", name: "buttonUrl", widget: "string"}
          - {label: "Overlay (Couleur avec opacité)", name: "overlay", widget: "string", default: "rgba(0, 0, 0, 0.5)"}
          - label: "SEO"
            name: "seo"
            widget: "object"
            fields:
              - {label: "Meta Title", name: "metaTitle", widget: "string"}
              - {label: "Meta Description", name: "metaDescription", widget: "text"}
              - {label: "Ville principale", name: "city", widget: "string"}
              - {label: "Métier", name: "profession", widget: "string"}